platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj 'NavigationMeshGraphExample.xcodeproj'

pod 'NavigationMeshGraph', :path => '../'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
